tuple=('python','java','c++','c','dart','flutter','go-lang','react.js','angular')
print(tuple)
print(type(tuple))
print("accessing a tuple to index:")
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print(tuple[6])
print(tuple[7])
print(tuple[8])
print("accssing a tuple neg index")
print(tuple[-0])
print(tuple[-1])
print(tuple[-2])
print(tuple[-3])
print(tuple[-4])
print(tuple[-5])
print(tuple[-6])
print(tuple[-7])
print(tuple[-8])